### ISSUE TITLE
Question react-redux: How to create Entity from JSON with new reference

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/js-sdk#11]
Hey there,

i have a short question:

I play around with baqend and react + react-redux. https://github.com/KillerCodeMonkey/baqend-blog-admin-react/tree/redux

The problem is, that the reducers should not manipulate the state directly. They should return new instances of objects or arrays, so the change-detection works and the views are rendered again.
I have a model called "Post". If an action updates a post like

```
post.save().then(updatedPost => dispatch(....)) 
```

the associated reducers are listening to this, but needs to return the post as a new object.

I tried something like that:

```
const postJSON = Object.assign({}, action.post.toJSON(), { acl: null })

return db.Post.fromJSON(postJSON)
```

1. Transforming the Post-instance to plain json (avoid errors --> set acl to null)
2. create a Post with fromJSON function

Sadly i get exact the same reference.

Do you have any ideas?

**Comment by fbuecklers** [comment]
Hi, 
that is a desired behavior, the SDK tracks id's to reference mappings. That ensures that you always get the same object for the same database object.

Additionally you can remove the id so the serialized object looses it's identity. fromJSON will then create a new object instead of updating the existing one. You can use `action.post.toJSON(true)` to create an json object without any metadata.(without id, version and ACL)

I'm not so familiar with react therefore I do not know if that really solve the problem for you. Is it required that a new copy must be provided always? My thought was, that only something must be changed on the reacts state to enforce a redraw.

Let me now if that helps.

**Comment by KillerCodeMonkey** [comment]
hey thanks for the explanation. i thought of this behavior. 

And you are write in plain react it is as easy as updating some key value and the renderer is triggered. 

But with redux you are introducing something like a global state and it behaves like this:
--> If you want to change the state you are defining function with the current state and the changed object as parameters. instead of directly manipulating the state you create a new state and return it.

In my case i do not want a complete new DB entity only the DB entity stored in a new object :).

Something like immutables. 

Keep the idea of event sourcing in your mind when thinking of redux:
1. you do not want side effects if you are manipulating something other application parts are based on
2. but you want a global app state, because app parts are sharing some data
3. You are defining a set of "actions" and "reducers", which handles your updates like a symbol/string-function mapping 
```
{ 
  "CREATE_POST": (current_state, updatedPost) =>  {
     // you would do something like this with pojo
     new_state = Object.assign({}, current_state, updatedPost);
      ...;
      return new_state;
  },
  ....
}
```

Sure i could decapsulate everything from baqend and dbentities --> passing the plain json, stuff my components. so if i want to ran an update, i would create the `db.Model.fromJSON()`.

Maybe you have another idea or could implement a simple trick, like passing an option for creating a new reference for an entity.

If not you can close this issue :)

**Comment by ErikWitt** [comment]
Hi,

I think there is another, easier workaround. You can wrap the dbobject into another javascript object without using toJSON and fromJSON:

```
{ 
  "CREATE_POST": (current_state, updatedPost) =>  {
     // you would do something like this with pojo
     post = {data: updatedPost};
      ...;
  },
  ....
}
```

Then you can access your post like this:

`var dbPostObject = post.data;`

This way you don't need to convert the object with toJSON and fromJSON all the time. I'm not that familiar with redux either but I hope this works :)

It's also not the prettiest thing in the word. We are discussing how to support this in the SDK but it's not that easy (see fbuecklers comment). If you have an idea, feel free to share it ;)

Best
Erik

**Comment by fbuecklers** [comment]
We have released our [react and react-native starter](https://www.baqend.com/guide/starter-kits/react/) + [redux middleware](https://github.com/Baqend/redux-baqend) which provides a better SDK integration into react.
I will close the issue for now.
