### ISSUE TITLE
SDK with Fusetools works on iOS and Mac but not on Android

### ISSUE THREAD

**Issue by israrwz** [Baqend/js-sdk#12]
I had to modify some parts of the baqend.js to make it work with Fusetools. The changes were required because Fusetools does not support `window.sessionStorage` but it has a shim for `window.localStorage` so i just changed the `sessionStorage` to `localStorage`.

Besides that in different places it tries to access the browser window api but as Fuse doesn't support it I had to change those parts as well. i.e I made the `isChrome` variable to `False` by default, similarly I changed 
`      if (secure === undefined) {
        secure = window.location.protocol == 'https:';
      }`

to 

`      if (secure === undefined) {
        secure = false;
      }`

and this line: `xhr.upload.onprogress = message.progress();` to this `xhr.onprogress = message.progress();`

These changes made it successfully work on local preview on MacOS and iOS but doesn't work on Android.

I hope together we can find a solution for it.

Thanks

**Comment by israrwz** [comment]
Okay, finally fixed it. The issue was with XMLHttpRequest polyfill in fusetools. i changed the getResponseHeader function from:

```
fuseXMLHttpRequest.prototype.getResponseHeader = function(header) {
    if(this._fuseHttpRequest === null) return;
    return this._fuseHttpRequest.getResponseHeader(header);
}
```
to :

```
fuseXMLHttpRequest.prototype.getResponseHeader = function(header) {
    if(this._fuseHttpRequest === null) return;
    if (!!this._fuseHttpRequest.getResponseHeader(header)){
        return this._fuseHttpRequest.getResponseHeader(header);
    } else {
        var heads = this._fuseHttpRequest.getResponseHeaders();
        var lines = heads.split("\n");
        var item = null;
        lines.forEach(function(line){
            if (line.indexOf(":")>-1){
                var keyvals=line.split(":");
                if (keyvals[0].toLowerCase()==header.toLowerCase())
                    item=keyvals[1].trimLeft();
            }
        });
        return item;
    }
}
```
It works now.

**Comment by fbuecklers** [comment]
Hi, 

I didn't get fusetools up and running on my local pc (windows 10) up to now, but i have added the fixes you have provided in the fusetools branch. Maybe you can verify if that fix the issues for you. 
Do you know where the fusetools polyfills and there issues are tracked? So we can provide them a patch as well?
Maybe you can share you project setup how you integrate baqend currently in your fuse project, since we have no experience with fuse up to now.
Thanks so far!

**Comment by fbuecklers** [comment]
Can u confirm?

**Comment by israrwz** [comment]
Hi @fbuecklers 

Sorry for the late response. I checked it, it doesn't work. It throws an error at line: 1749 saying "The EntityManagerFactory is already connected".

In my original solution I had that lined commented out, but even if I comment it out in your commit it won't work.

**Comment by israrwz** [comment]
I made it working by making following changes:
EntityManagerFactory.prototype.connect function:

```
   EntityManagerFactory.prototype.connect = function connect(hostOrApp, port, secure, basePath) {
    //if (this._connector) throw new Error('The EntityManagerFactory is already connected.');
    if (this._connector) {
      this._connected();
      return this.ready();
    }
    if (Object(port) instanceof Boolean) {
      secure = port;
      port = 0;
    }

    this._connector = Connector.create(hostOrApp, port, secure, basePath);

    this._connected();
    return this.ready();
  };
```

**Comment by fbuecklers** [comment]
Hi, I will close the issue for now. Since we have applied all required changes to be compatible in Fusetools.
We can track the progress of the realtime part in the [Fusetools Forum](https://www.fusetools.com/community/forums/general/cannot_connect_to_baqend_websocket_server)
