### ISSUE TITLE
Modify Schema from javascript SDK

### ISSUE THREAD

**Issue by ptpaterson** [Baqend/js-sdk#16]
Is it possible to modify the schema from the clien (javascript SDK)t?  Am I missing functionality already here?

I would like to make changes programmatically.  Perhaps this should be guarded with Roles.

I spent some time digging into the documentation but didn't find anything suggesting that this could be done, but I very well may be overlooking.

**Comment by Macragge** [comment]
Hey,
that is definetly possibly. To be fair though, it is not documented enough right now. Here is how you would do it:

// You create a Factory-Object
let emf = new DB.EntityManagerFactory({ host: 'your-app-name' });
// Create a db instance whos user is shared with the metamodel
let em = emf.createEntityManager(true);
// Wait on the db initialization
await em.ready();
// Login with a user who has admin permissions
await em.User.login("admin", "password");
// Get the corresponding metamodel
let metamodel = emf.metamodel;
// You can now add new types to this metamodel
metamodel.addType(personType = new DB.metamodel.EntityType('Person', metamodel.entity(Object)));
//  And lastly you can add attributes to your generated types
personType.addAtttribute(new DB.metamodel.SingularAttribute('name', metamodel.baseType(String)));
// Save your metamodel afterwards to update the schema
await metamodel.save(); 

Hope this helps. 

Sven
