### ISSUE TITLE
Support mobX.js observables

### ISSUE THREAD

**Issue by misantronic** [Baqend/js-sdk#19]
Please visit this issue for clarification:
https://github.com/mobxjs/mobx/issues/1468

the main problem is that mobx observables won't react to changes on the Proxy-properties returned by baqend. the author of mobx claims that this cannot be an issue with mobx itself but the implementation of the proxy. somehow it is not possible to make them observable.

my workaround for this is to create an object-literal from to proxy-data with `.toJSON()` and re-create the Proxy later when saving, deleting etc. via `.fromJSON()`. This kind of works but is not free of implications when handling Dates or Files.

See my workaround:

```js
function createViewModel<T>(
    Class: binding.EntityFactory<any>,
    item: binding.Entity,
    type?: misc.Type,
    refViewModel?: misc.ViewModel
): T {
    const viewModel: T & misc.ViewModel<T> = item.toJSON({
        depth: true
    }) as any;

    // convert all date-values and images
    [...Object.keys(Class.prototype), 'key'].forEach(key =>
        preserveItemValues(item, key, viewModel)
    );

    viewModel.restore = async function() {
        // `fromJSON` doesn't consider Dates
        // specify which dates will be formated
        const keepValues = Object.entries(this).reduce(
            (memo, [key, value]) => {
                if (value instanceof Date) {
                    return [...memo, { key, value }];
                }

                return memo;
            },
            [] as { key: string; value: any }[]
        );

        const item = Class.fromJSON(this);

        // assign values to be kept
        keepValues.forEach(({ key, value }) => (item[key] = value));

        // sync changes back to ref-viewModel
        if (refViewModel) {
            Object.keys(Class.prototype).forEach(key => {
                refViewModel[key] = this[key];
            });
        }

        return item;
    };

    viewModel.ref = item;
    viewModel.type = type;
    viewModel.isViewmodel = true;

    return viewModel;
}
```

I would love to see real support for mobx observables in the future :)

**Comment by misantronic** [comment]
To whom it may concern, I created a much more complex workaround which pretty much covers all my use-cases regarding `mobx`:
https://gist.github.com/misantronic/83c41bc89aa4ce44c3ed8213dc75a32d

Usage is pretty simple:

the original baqend-entity is wrapped in a viewmodel:

`const viewmodel = toJSON(entitiy);`

you can always access the original via `viewmodel.$ref`
most of the entity-methods are available e.g. save, update, insert, delete, ...
when changing data on the viewmodel (e.g. by saving), all changes are reflected to all instances of this viewmodel.

**Comment by fbuecklers** [comment]
Hi,
i have take a deeper look in mobx and it seems that the only problem is, that mobx do not enhance es6 class objects by default. this can be solved by manually wrap our loaded objects into observables afterwards.

Note that the new snapshot SDK is still needed to work properly

Here is a simple example how it should work:
```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import { extendObservable, observable } from 'mobx'
import {observer} from 'mobx-react';
import {model, db} from 'baqend';
import DevTools from 'mobx-react-devtools';

class AppState {
  @observable public item: model.AclPerson = null

  constructor() {
    this.connect();
  }

  async connect() {
    await db.connect("<your-app>", true);
    const item = await db.AclPerson.load('/db/AclPerson/6490cc66-901d-425a-bd98-31a5e39dc7c4');
    this.item = extendObservable(item, item); // we wrap here the loaded object in a mobx observable, since mobx will not enhance instances of es6 classes per default
  }

  async changeName() {
    this.item.name = 'New Name ' + Math.floor(Math.random() * 100);
    console.log(this.item.name)
    await this.item.save();
  }
}

@observer
class TimerView extends React.Component<{appState: AppState}, {}> {
    render() {
        return (
            <div>
                <button onClick={this.onReset}>
                    Name: {this.props.appState.item && this.props.appState.item.name}
                </button>
                <DevTools />
            </div>
        );
     }

     onReset = () => {
         this.props.appState.changeName();
     }
};

const appState = new AppState();
ReactDOM.render(<TimerView appState={appState} />, document.getElementById('root'));
```

**Comment by misantronic** [comment]
Thank you for your effords!
I actually couldn't make it work using `extendObservable`. Still, there is another way which kind of works; using `decorate`:

```js
import { decorate, observable } from 'mobx'

...

decorate(
    item,
    Object.keys(item).reduce(
        (memo, key) => ({ ...memo, [key]: observable }),
        {}
    )
);
```

I am in production using my viewModel-wrapper for quite a while which does a lot for me. It will take a lot of work to get back to using no viewModel.
The `acl`-management is still a bit difficult to handle. Changes performed by `allowReadAccess` for example are not recognized by the observable.
