### ISSUE TITLE
Not compatible with RxJs 6

### ISSUE THREAD

**Issue by harishreddy-m** [Baqend/js-sdk#23]
Using baqend 2.13.0 in angular 7 project.

There is a compile time error after using resultStream() instead of resultList().

Error:
``` 
   Type 'import("/home/harishm/xxx/node_modules/baqend/node_modules/rxjs/Observable").Observable<any>' is not assignable to type 'import("/home/harishm/xxx/node_modules/rxjs/internal/Observable").Observable<any>'.
      Property 'operator' is protected in type 'Observable<any>' but public in type 'Observable<any>'. [2322]
```
rxjs/internal/Observable is conflicting with /rxjs/Observable

![image](https://user-images.githubusercontent.com/592646/50732022-00455b00-1172-11e9-88f3-0cb9d69f8abf.png)

**Comment by harishreddy-m** [comment]
Using 
`import { db, model } from 'baqend/realtime';`

**Comment by harishreddy-m** [comment]
After using resultList() 

I have this error in Browser

`ERROR TypeError: "baqend_realtime__WEBPACK_IMPORTED_MODULE_1__.db.MyClass is undefined`

**Comment by fbuecklers** [comment]
Okay thanks for the hint, we may put rxjs to the SDK as a peer dependency!
For your later issue can you share a code snippet which causes the error?
It seems that the db is not ready when you are using it. As described in our guide at https://www.baqend.com/guide/topics/getting-started/#connect-your-app-to-baqend

**Comment by harishreddy-m** [comment]
It is a angular project.

I used resolve in routing for the component as shown in starter project.

I will check again.

**Comment by harishreddy-m** [comment]
Ok. 
resolve: { db: DBReady } in routing alone is not sufficient.

wrapping my method like like this removed "ERROR TypeError: "baqend_realtime__WEBPACK_IMPORTED_MODULE_1__.db.MyClass is undefined"
```
ngOnInit() {
        db.ready().then(function() {
        this.myMethod()
        });
    }
```

Will you create a separate issue for RxJs peer dependency.I will close this.

**Comment by harishreddy-m** [comment]
Now I am seeing this error:

![image](https://user-images.githubusercontent.com/592646/50750930-9a2b0780-1247-11e9-99ab-e01b31f10914.png)

After taking a breakpoint, I noticed there is a call to send(event) method with undefined as argument.

**Comment by fbuecklers** [comment]
Should be solved in the latest release.
