### ISSUE TITLE
Can't find variable: open

### ISSUE THREAD

**Issue by acmngmbh** [Baqend/js-sdk#25]
I am trying to start a Facebook oAuth login flow from my expo.io app with the following code:

`  _PressLearnMore = () => {
      db.User.loginWithFacebook("xxx").then((user) => {
        db.User.me == user;
    });
  };`

An error raises immediately:

> Can't find variable: open
> EntityManager.js:976:9

**Comment by fbuecklers** [comment]
Solved in 3.1
