### ISSUE TITLE
`baqend deploy` skips first file in files array

### ISSUE THREAD

**Issue by lionralfs** [Baqend/js-sdk#46]
Hey,

I just noticed that a file from my static files deployment was missing. I did some digging and stumbled upon this line:
https://github.com/Baqend/js-sdk/blob/c3062949ac8f671e6043e744a5f7728a1c2bacc4/cli/deploy.ts#L144

`index += 1` evaluates to the updated value of index, so the first element in `files` is always skipped.

I'm sure it could be fixed easily by moving the update expression out of the array index:
```ts
const file = files[index];
index += 1
```

**Comment by fbuecklers** [comment]
Hi @lionralfs 

Thanks for reporting that issue. 
It is fixed in the latest release.
