### ISSUE TITLE
"Precondition Failed - 412" when using the depth option on queries

### ISSUE THREAD

**Issue by oles** [Baqend/js-sdk#47]
Hey!

I'm updating an old app, and thought I'd try to update the baqend SDK it uses.

After updating from 2.14.1 to 3.1.4, I keep on getting

```
{
    "status": 412,
    "message": "Precondition Failed"
}
```

On seemingly all the queries that use the depth option, for example

```
import {db as baqend} from 'baqend'

baqend.ActivityCategory
    .find()
    .equal('id', category)
    .singleResult({depth: 1})
```

I sadly don't have the time to troubleshoot this further now, maybe there's just something weird in our setup. 

I'll get back to troubleshooting sometime next week. Do you have any suggestions until then, @fbuecklers? :crossed_fingers:

**Comment by oles** [comment]
I've narrowed it a little down;

2.14.1
![Screenshot from 2021-10-15 13-00-29](https://user-images.githubusercontent.com/7634050/137477629-33fae942-0b76-4dfd-8cd0-e4fa03417afd.png)

3.1.4
![Screenshot from 2021-10-15 13-00-13](https://user-images.githubusercontent.com/7634050/137477613-ed18b24e-613b-4c0f-a3cc-eec609bfde25.png)

Seems 3.1.4 is not doing the automatic GET request anymore, which seems to be because of the depth parameter.

Researching further...

**Comment by fbuecklers** [comment]
Hi @oles can you still reproduced that?

We had indeed an issue with our CDN which cause some unexpected behaviors which was triggered by a change of them.
This issue is fixed since few months. I can't reproduce the issue in our tests.

**Comment by oles** [comment]
Hey! Yes, just did, and I sent you an email with a cURL copy of one of the failing requests 👍

**Comment by fbuecklers** [comment]
Thanks Ole for the additional details and the curl request. It was indeed an issue at our CDN integration and the new SDK.
It should be fixed now, and it will do not need a new SDK version for it. 

Please let me know if everything works on your side as well now.

**Comment by oles** [comment]
Works!! Thank you :)
