### ISSUE TITLE
JS SDK does not support listing all users.

### ISSUE THREAD

**Issue by AlvaroMolano** [Baqend/js-sdk#6]
Hi,
Are you planing to implement a load for all users?
Thanks.

**Comment by AlvaroMolano** [comment]
Trying to load user list through API '`GET: /v1/db/User`' works using a root token but does not work if the request is made from a different user's token with ***admin (/db/Role/1).*** role.


   ` "id": "/db/User/11",
    "version": 5,
    "acl": {
      "read": {
        "/db/Role/1": "allow"
      },
      "write": {
        "/db/Role/1": "allow"
      }`
    

`GET: /v1/db/User` returns 466 permission denied

**Comment by hannes-k** [comment]
Hi,

by default all users get an read and write ACL on object level. Only the the user himself and admins are allowed to load them. We do this to protect the users data like emails.

Users, which are included in the admin Role, are allowed to load the users. 
You can try it with the following example:

```js
DB.User.load('14').then(user => { // My test user
	DB.Role.load('1').then(role => { // 1 is the ID of the admin role
		role.addUser(user); // adds the user to the admin role
		role.save(); // saves the role
	});
});
```

After adding the user to the admin role, you are allowed to load the users:

```js
DB.User.logout().then(() => {  // make sure you are logged out
	return DB.User.login('test', 'test'); // is my test user with the id 14
}).then(() => { 
	return DB.User.find().resultList(); // loads all users
}).then(users => console.log(users));
```

Best regards
Hannes

**Comment by hannes-k** [comment]
If you have any further questions, please create a new ticket or use our Stackoverflow Tag: [Baqend](https://stackoverflow.com/questions/tagged/baqend)
