### ISSUE TITLE
Accessing Files 

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/js-sdk#8]
Hey there,

i've tried to show an image in my app. 
I have a model with an attribute `preview_image` of type File and an reference to a file in `/file/www/images/...`.

Now i want to show this image in my app using the way provided in your guide.

```
let file = new db.File(post.preview_image)
```

But it does not work.
I tried the other approach like:

```
post.load()
```

or 

```
db.Post.resultList({ depth: true})
```

to get all referenced objects without an extra operation.
But with no luck.

How should i do it?

Thanks you!

**Comment by fbuecklers** [comment]
Hi,

if you use the File type as an attributes type it is already an db.File instance. Therfore you can directly use the `post.preview_image.url` property. Als describe in our guide as [embedded files](https://www.baqend.com/guide/#embedded-files). 

An full example would looks like the following:
```js
db.Post.find().singleResult().then(function(post) {
  var imgSrc = post.preview_image.url;
});
```
Best Florian

**Comment by KillerCodeMonkey** [comment]
d'oh!

i will try it. Thanks for your quick response, the `load()` in the documentation confused me a little bit

And again thanks for your support!
Nice to see a german competitor in the paas world 👍 

If you need help in some cases where i can help. Let me know :)

**Comment by KillerCodeMonkey** [comment]
@fbuecklers 

Sorry i need to bother you again.

If i try to access the file in TypeScript in the way you described
```
db.Model.find()
    .singleResult()
    .then((post: model.Post) => {

      return post;
  });
```

then i get the following object as result for the file:
<img width="1370" alt="bildschirmfoto 2017-01-24 um 20 31 20" src="https://cloud.githubusercontent.com/assets/2264672/22263285/3747f57e-e274-11e6-9504-a434509ab86f.png">


If i am init the File manually like this:
```
const previewImage = new db.File('/file/www/images/posts/avatar.jpg') as binding.File;
```
The result looks like this and seems to be a little bit more correct... but there are many PersistentError
<img width="583" alt="bildschirmfoto 2017-01-24 um 20 28 06" src="https://cloud.githubusercontent.com/assets/2264672/22263124/aef8e700-e273-11e6-96c9-44da726fb0ab.png">

**Comment by fbuecklers** [comment]
Yes,
The PersistentError cause because the metadata of a file must be fetched before it can be used. The behavior is similar to object references.

The metadata can be fetched explicitly or is fetched when the file content is loaded.
An example is also in the guide at https://www.baqend.com/guide/#metadata.

**Comment by KillerCodeMonkey** [comment]
And the error `Cannot read property 'createUrl' of undefined at File.get` when accessing the the model file attribute directly?

Thanks again and again and again 🌹

**Comment by fbuecklers** [comment]
Hm,
It seems to be an issue in the SDK. I will reopen the issue and will give here an update when it is resolved.
I think we will release the fix in the next few days.
Thanks for reporting it.

**Comment by fbuecklers** [comment]
Hi,
just want let you know that the new release with the fix is released.
Cheers

**Comment by KillerCodeMonkey** [comment]
great thanks again, dude!

cheers
