### ISSUE TITLE
Linebreaks and new lines are not save in Attributes type String

### ISSUE THREAD

**Issue by KillerCodeMonkey** [Baqend/js-sdk#9]
hey there,

i recognized that if i try to save text of an textarea with newlines, the line breaks are gone after i save the entry.

I want to store markdown in a next step of my blog application and without linebreaks this would be difficult.

Is this known or unwanted or is there something like special type for that purpose?

Thanks in advance.

**Comment by malte-lau** [comment]
Hi Bengt,
there is a bug in the Dashboard preventing the insertion of line breaks.
We will fix that in one of the next updates.

Using the SDK it should work fine.
I run this in the console of the Dashboard:
```js
var todo = new DB.Todo({id: 'Todo1', name: 'My' + '\n' + 'first' + '\n' + 'Todo'});
todo.save()
```
```js
DB.Todo.load('Todo1').then(function(obj) {
  console.log(obj.name);
});
//My
//first
//Todo
```
So here it worked. 

Best Regards
Malte

**Comment by KillerCodeMonkey** [comment]
ah sorry, i meant over the dashboard. Is there a specific repository for dashboard and its issues?

**Comment by malte-lau** [comment]
No, not yet. Thank you for posting the issue here. I was just not sure, that this is not an SDK bug.
We might create a repository for the dashboard, great suggestion.

I hope we have the bug fixed soon, sorry for the inconvinience. 

Best
Malte

**Comment by fbuecklers** [comment]
Hi,
we have fixed the issue in the latest dashboard release. Therefore I will close the issue for now.
